### ISSUE TITLE
Move Timer

### ISSUE THREAD

**Issue by sigvaldm** [puncproject/PUNCpp#16]
Timer doesn't have anything to do with injection. diagnostics.h would be a more appropriate place for this class.

**Comment by diakodarian** [comment]
Timer has been moved to diagnostics.h

**Comment by sigvaldm** [comment]
A possible improvement would be to move the methods to diagnostics.c (leaving the documentation in the .h-file). Didn't think about this when I first wrote this issue. Do not prioritize.
