### ISSUE TITLE
`override_status_print` broken.

### ISSUE THREAD

**Issue by sigvaldm** [puncproject/PUNCpp#25]
The fix of https://github.com/puncproject/PUNCpp/issues/3 broke some code in `interaction.cpp`. The `override_status_print` variable does not work anymore (which used to toggle whether to print a new line each update or just re-print on the same line). Do you think we could implement a similar functionality in Timer?

**Comment by diakodarian** [comment]
Sorry about this. I'll have a look.

**Comment by diakodarian** [comment]
Yes, we can add this functionality to Timer.

**Comment by diakodarian** [comment]
Fixed.
