### ISSUE TITLE
Bug in Timer in "overwrite mode"

### ISSUE THREAD

**Issue by sigvaldm** [puncproject/PUNCpp#28]
`Time remaining: 0 d 0:1:90`

Surely, it shouldn't say 1 minute and 90 seconds. What's happened is that it was `0:1:10` and then it's overwritten by `0:1:9` but not the 0 which extends one character further to the right. An easy fix would be to lock hours, minutes and seconds to always use 2 digits (although a similar bug could arise when going from 10 to 9 days). Another option would be to write additional empty spaces afterwards.

**Comment by diakodarian** [comment]
Fixed. Later, I'll make the formatting and printing more generic.
