### ISSUE TITLE
Collect mesh quantities in Mesh class

### ISSUE THREAD

**Issue by sigvaldm** [puncproject/PUNCpp#32]
And standardize boundary id's.

**Comment by sigvaldm** [comment]
I'll do some work on this, then throw it over to you @diakodarian.

**Comment by sigvaldm** [comment]
I'm done. You can merge in `exterior_boundaries` now @diakodarian. Perhaps `Facet` belong in `mesh.h` as well?

**Comment by diakodarian** [comment]
I'm on it.

**Comment by diakodarian** [comment]
Done!
