### ISSUE TITLE
Bug in ne.pvd and ni.pvd?

### ISSUE THREAD

**Issue by sigvaldm** [puncproject/PUNCpp#37]
When animating ne in ParaView for a longer duration, values quickly rise to above 1e100, before ParaView crashes. I use

```
[diagnostics]
n_fields = 10
n_state = 0
fields_end = true
state_end = true
PE_save = false
densities_ema = false
densities_tau = 1e-6
```

Is this something I'm doing wrong or some bug in ParaView or is it in PUNC++?

**Comment by diakodarian** [comment]
I had a test run, and got the same behavior. I think it's PUNC++. I'll have a closer look.

**Comment by diakodarian** [comment]
Fixed.

**Comment by sigvaldm** [comment]
Damn! That was fast.
