### ISSUE TITLE
FieldWriter

### ISSUE THREAD

**Issue by sigvaldm** [puncproject/PUNCpp#52]
This is a very non-reusable way to write code:

`FieldWriter fields("Fields/phi.pvd", "Fields/E.pvd", "Fields/rho.pvd", "Fields/ne.pvd", "Fields/ni.pvd");`

What if I in some cases need to not save `ne` and `ni`? If it had been written to do one thing only it would be much more reusable, and in my opinion, easier to read:

```
FieldWriter fields("Fields/phi.pvd");
FieldWriter fields("Fields/rho.pvd");
```

It means more lines, but very similar lines that are fast to read and easy to understand.

**Comment by sigvaldm** [comment]
Have you started on this? I may need to do some changes.

**Comment by diakodarian** [comment]
No, I have not. Go ahead if want to do some changes.

**Comment by sigvaldm** [comment]
Good!

**Comment by sigvaldm** [comment]
This one is now complete. I needed EMA-filtered phi for my current research, while getting the unfiltered phi for comparison, so this is how it works now:

- One option `save_fields_on_exit` to save all fields at the end of the simulation (like before)
- Save fields at specified physical periods. One option per field, e.g. `period_phi=1e-6` saves phi at every microsecond. This is more convenient than specifying in terms of timesteps, because it is easier to know how often to sample in terms of physical quantities, and because it keeps the "frame rate" of the video constant when changing the time-step of the simulation. Zero deactivates saving.
- One relaxation time for each field, e.g. `tau_phi` for phi. The filtered result is saved in a separate file for comparison, and deactivated by setting it to zero.

I don't really think we need different relaxation times and periods for the different fields, but it is useful to be able to turn on/off saving and filtering individually, and rather than having one relaxation time and one saving period plus two booleans for each field to turn it on/off, I just specify the times for each field, with zero to deactivate. Simpler and more flexible.
