### ISSUE TITLE
Coarse particle statistics in history.dat

### ISSUE THREAD

**Issue by sigvaldm** [puncproject/PUNCpp#62]
For faster particles, a smaller timestep is needed to get a good solution. For this reason we often specify dt in terms of the characteristic time 1/omega_pe of the plasma. However, in presence of objects with fixed voltage, the objects accelerate the particles. Because higher voltages cause more acceleration, it is reasonable to believe that a smaller timestep is necessary for simulations of objects with high voltages.

It might be useful if the history.dat file could contain some rough statistics about the speed of the particles, for instance one column for mean value and one for standard deviation for both positive and negative particles. A good algorithm for such computations that I have used in TaskTimer is Welford's algorithm. This could be turned off in the input file similar to compute_potential_energy. I don't think it should be much slower than just counting the particles.

**Comment by diakodarian** [comment]
Done.

**Comment by sigvaldm** [comment]
Cool! Have you checked if you observe an increase in mean value for simulations with high voltage objects?

**Comment by sigvaldm** [comment]
Sorry, but having looked at the implementation, I don't consider this task complete. I'm re-opening it.

The implementation of Welford's algorithm looks good, but why does it just lie around in ``History::save()``? This is a function for saving, not for computing stuff. The computation should be in a separate function, for instance `Population::statistics()`. 

If we want to keep PUNC at least slightly maintainable and reliable, it is very important that we clean up after ourselves when implementing new functionality. We have not always had the opportunity to do so when working towards a scientific deadline and needs something quickly, but I think it should be the norm.

**Comment by diakodarian** [comment]
I agree. I'll move it to a separate function.

**Comment by sigvaldm** [comment]
Looks good!
